name: Download Weather Map Hourly

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Download weather map with timestamp
        run: |
          mkdir -p archive

          filename="archive/US_$(date -u '+%Y%m%d_%H00').png"

          curl -fL \
            "https://www.weather.gov/wwamap/png/US.png" \
            -o "$filename"

          echo "Saved $filename"

      - name: Create image list
        run: |
          ls archive/*.png | sed 's#^#"#;s#$#",#' | sed '$s/,$//' > archive/images.json
          sed -i '1s/^/[/; $s/$/]/' archive/images.json

      - name: Commit files
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add archive/

          git commit -m "Weather map update $(date -u)" || exit 0

          git push
